"use client";

import { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";

export function FaqSection() {
    const [openIdx, setOpenIdx] = useState<number | null>(0);

    const faqs = [
        {
            q: "Will DistroAI work with my existing Tally Prime or Tally ERP 9?",
            a: "Yes, 100%. DistroAI includes a lightweight desktop bridge that connects securely to your Tally instance on http://localhost:9000. It reads ledger balances and posts sales vouchers and receipts automatically in real time without altering your Tally company configuration.",
        },
        {
            q: "Do my retailers need to install any new app to order?",
            a: "No app required for retailers! Retailers continue ordering via WhatsApp just like they do today. They can type in plain English, Hindi, or Hinglish (e.g. 'Bhai 10 peti Fortune oil bhej do') or send a photo of their handwritten order slip. The AI bot parses the order, confirms stock, and returns a verified invoice.",
        },
        {
            q: "What happens if a field sales rep loses internet connection in rural areas?",
            a: "The DistroAI SFA Mobile App is designed with an offline-first architecture. Sales reps can view cached product catalogs, take retailer orders, and record GPS beat check-ins completely offline. All queued orders automatically sync to your cloud server the moment network connectivity resumes.",
        },
        {
            q: "How does the Dynamic UPI QR on invoices help with collections?",
            a: "Every invoice generated by DistroAI embeds an NPCI-compliant dynamic UPI QR code containing the exact bill amount and invoice reference. When retailers receive the invoice PDF on WhatsApp or physical printout, scanning it with Google Pay, PhonePe, or Paytm automatically populates the exact amount and invoice number, eliminating typo errors and automating ledger reconciliation.",
        },
        {
            q: "How is our business financial data protected and backed up?",
            a: "DistroAI enforces multi-tenant PostgreSQL Row-Level Security (RLS) so your inventory, customer margins, and ledger data can never be viewed by another distributor. Continuous WAL-G database archiving creates encrypted point-in-time recovery backups to Backblaze B2, satisfying the enterprise 3-2-1 backup standard.",
        },
        {
            q: "How long does onboarding and catalog setup take?",
            a: "Most distributors are live in under 15 minutes. You can import your existing product catalog and retailer master list via a simple Excel/CSV upload or directly from your Tally company export.",
        },
    ];

    const toggle = (idx: number) => {
        setOpenIdx(openIdx === idx ? null : idx);
    };

    return (
        <section id="faq" className="py-24 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14 space-y-3">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[var(--gold)]/10 text-[var(--gold)] text-xs font-semibold uppercase tracking-wider">
                    <HelpCircle size={14} />
                    <span>Got Questions?</span>
                </div>
                <h2
                    className="text-3xl sm:text-4xl font-bold text-[var(--text-primary)]"
                    style={{ fontFamily: "var(--font-playfair)" }}
                >
                    Frequently Asked Questions
                </h2>
                <p className="text-[var(--text-secondary)] text-sm sm:text-base">
                    Everything you need to know about DistroAI's setup, security, and Tally integration.
                </p>
            </div>

            <div className="space-y-4">
                {faqs.map((faq, idx) => {
                    const isOpen = openIdx === idx;

                    return (
                        <div
                            key={idx}
                            className={`rounded-xl border transition-all duration-200 overflow-hidden ${
                                isOpen
                                    ? "border-[var(--border-accent)] bg-[var(--bg-card)] shadow-lg"
                                    : "border-[var(--border)] bg-[var(--bg-secondary)]/60 hover:border-[var(--border-accent)]/50"
                            }`}
                        >
                            <button
                                onClick={() => toggle(idx)}
                                className="w-full py-4 px-6 text-left flex items-center justify-between gap-4 font-semibold text-sm sm:text-base text-[var(--text-primary)]"
                            >
                                <span>{faq.q}</span>
                                <ChevronDown
                                    size={18}
                                    className={`text-[var(--gold)] shrink-0 transition-transform duration-200 ${
                                        isOpen ? "rotate-180" : ""
                                    }`}
                                />
                            </button>
                            {isOpen && (
                                <div className="px-6 pb-5 pt-1 text-xs sm:text-sm text-[var(--text-secondary)] leading-relaxed border-t border-[var(--border)]/50">
                                    {faq.a}
                                </div>
                            )}
                        </div>
                    );
                })}
            </div>
        </section>
    );
}
