export const PLAN_LIMITS = {
    FREE: {
        maxUsers: 1,
        maxMonthlyInvoices: 100,
        maxProducts: 50,
        maxCustomers: 100,
        maxAiQueriesPerMonth: 50,
        features: {
            whatsappBot: false,
            salesmanApp: false,
            shelfAudit: false,
            advancedAnalytics: false,
            tallySync: false,
            apiAccess: false,
            customerPortal: false,
            metaAds: false,
        },
    },
    STARTER: {
        maxUsers: 5,
        maxMonthlyInvoices: 999999,
        maxProducts: 500,
        maxCustomers: 1000,
        maxAiQueriesPerMonth: 250,
        features: {
            whatsappBot: true,
            salesmanApp: false,
            shelfAudit: false,
            advancedAnalytics: false,
            tallySync: true,
            apiAccess: false,
            customerPortal: true,
            metaAds: false,
        },
    },
    GROWTH: {
        maxUsers: 10,
        maxMonthlyInvoices: 999999,
        maxProducts: 999999,
        maxCustomers: 999999,
        maxAiQueriesPerMonth: 1000,
        features: {
            whatsappBot: true,
            salesmanApp: true,
            shelfAudit: true,
            advancedAnalytics: true,
            tallySync: true,
            apiAccess: false,
            customerPortal: true,
            metaAds: true,
        },
    },
    ENTERPRISE: {
        maxUsers: 999999,
        maxMonthlyInvoices: 999999,
        maxProducts: 999999,
        maxCustomers: 999999,
        maxAiQueriesPerMonth: 999999,
        features: {
            whatsappBot: true,
            salesmanApp: true,
            shelfAudit: true,
            advancedAnalytics: true,
            tallySync: true,
            apiAccess: true,
            customerPortal: true,
            metaAds: true,
        },
    },
} as const;

export type PlanName = keyof typeof PLAN_LIMITS;
export type FeatureName = keyof typeof PLAN_LIMITS.FREE.features;
