import { Html, Head, Body, Container, Text, Heading, Section } from '@react-email/components';
import React from 'react';

export const WeeklyDigestEmail = (props: {
    firstName: string;
    data: Record<string, unknown>;
}) => (
    <Html>
        <Head />
        <Body style={{ backgroundColor: '#0e0c15', color: '#f0e8d5', fontFamily: 'sans-serif' }}>
            <Container style={{ margin: '0 auto', padding: '32px', maxWidth: '600px', backgroundColor: '#1a1625', borderRadius: '12px' }}>
                <Heading style={{ color: '#d4a843', fontSize: '24px', margin: '0 0 20px 0' }}>Weekly Business Digest</Heading>
                <Text style={{ fontSize: '16px', lineHeight: '24px' }}>
                    Hi {props.firstName}, here is your business summary for the past week:
                </Text>

                <Section style={{ backgroundColor: '#2a2436', padding: '16px', borderRadius: '8px', margin: '20px 0' }}>
                    <Text style={{ margin: 0, fontSize: '14px', fontFamily: 'monospace', color: '#c0b6a4', whiteSpace: 'pre-wrap' }}>
                        {JSON.stringify(props.data, null, 2)}
                    </Text>
                </Section>

                <Text style={{ color: '#9a9080', fontSize: '12px', marginTop: '24px' }}>
                    Generated by DistroAI Analytics. Open the dashboard for beautiful charts and deep dives.
                </Text>
            </Container>
        </Body>
    </Html>
);

export default WeeklyDigestEmail;
